baseURL = "https://antelang.org/"
title = "Ante"

theme = "hugo-universal-theme"

languageCode = "en-us"
defaultContentLanguage = "en"

newContentEditor = "vim"

[params]
  viewMorePostLink = "/blog/"
  mainSections = ["blog"]
  description = "For exploring algebraic effects, safe shared mutability, and other novel features"
  author = "Jake Fecher"
  defaultKeywords = ["ante", "programming", "language", "antelang", "lang"]
  date_format = "2006-01-02"
  style = "red"
# default, blue, green, marsala, pink, red, turquoise, violet

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    style = "monokai"
    codeFences = true

[menu]

# Top bar with social icons
[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-github"
    title = "The compiler is on GitHub"
    subtitle = "All are welcome to contribute!"
    link_url = "https://github.com/jfecher/ante"
    link_text = "github.com/jfecher/ante"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Recent posts"
    subtitle = "Read the latest blog posts"

[taxonomies]
  category = "categories"
  tag = "tags"
  authors = "authors"
